
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FLOAT_LIT = 37;
  public static final int UMINUS = 41;
  public static final int UPLUS = 42;
  public static final int NOTEQUAL = 15;
  public static final int LPAREN = 6;
  public static final int GREATER = 12;
  public static final int SEMI = 2;
  public static final int CONTINUE = 27;
  public static final int UNOT = 43;
  public static final int INT = 32;
  public static final int LESS = 10;
  public static final int FOR = 29;
  public static final int MINUS = 4;
  public static final int RPAREN = 7;
  public static final int NOT = 18;
  public static final int AND = 17;
  public static final int LESSEQUAL = 11;
  public static final int OR = 16;
  public static final int COMMA = 24;
  public static final int DIV = 8;
  public static final int COMM = 9;
  public static final int PLUS = 3;
  public static final int ASGOP = 19;
  public static final int IF = 31;
  public static final int ID = 40;
  public static final int EOF = 0;
  public static final int BOOLEAN = 25;
  public static final int RETURN = 33;
  public static final int EQUAL = 14;
  public static final int error = 1;
  public static final int LCURLY = 20;
  public static final int BREAK = 26;
  public static final int VOID = 34;
  public static final int RCURLY = 21;
  public static final int GREATEREQUAL = 13;
  public static final int TIMES = 5;
  public static final int BOOLEAN_LIT = 38;
  public static final int ELSE = 28;
  public static final int LSQUARE = 22;
  public static final int WHILE = 35;
  public static final int RSQUARE = 23;
  public static final int FLOAT = 30;
  public static final int STRING_LIT = 39;
  public static final int INT_LIT = 36;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "DIV",
  "COMM",
  "LESS",
  "LESSEQUAL",
  "GREATER",
  "GREATEREQUAL",
  "EQUAL",
  "NOTEQUAL",
  "OR",
  "AND",
  "NOT",
  "ASGOP",
  "LCURLY",
  "RCURLY",
  "LSQUARE",
  "RSQUARE",
  "COMMA",
  "BOOLEAN",
  "BREAK",
  "CONTINUE",
  "ELSE",
  "FOR",
  "FLOAT",
  "IF",
  "INT",
  "RETURN",
  "VOID",
  "WHILE",
  "INT_LIT",
  "FLOAT_LIT",
  "BOOLEAN_LIT",
  "STRING_LIT",
  "ID",
  "UMINUS",
  "UPLUS",
  "UNOT"
  };
}

